services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=userpass'
      - 'MYSQL_ROOT_PASSWORD=rootpass'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'